version: "3.8"

services:

  rabbitmq:
    container_name: backend-geloextra-rabbitmq
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"      
    hostname: rabbit
    networks:
      geloextra-network:
        ipv4_address: 172.20.0.3

  backend:

    build:
      context: .
      dockerfile: Dockerfile
    command: ["bash", "/app/start.sh"]
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    networks:
      geloextra-network:
        ipv4_address: 172.20.0.4



networks:
  geloextra-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
